version: '3.3'

networks:
    consul-network:

services:
    server:
        image: consul:latest
        networks:
            consul-network:
                aliases:
                    - consul.server
        command: "consul agent -config-file /consul/config/server.json"
        ports:
            - "8500:8500"
            - "8600:8600/udp"
        volumes:
            - ./config:/consul/config
        deploy:
#            mode: replicated
#            replicas: 3
#            endpoint_mode: dnsrr
#            update_config:
#                parallelism: 1
#                failure_action: rollback
#                delay: 30s
#            restart_policy:
#                condition: any
#                delay: 5s
#                window: 120s
            placement:
                constraints:
                    - node.role == manager
    consul-agent-1:
        image: consul:latest
        networks:
            - consul-network
        command: "consul agent -config-file /consul/config/client.json"
        volumes:
            - ./config:/consul/config
    visualizer:
        image: dockersamples/visualizer:stable
        ports:
            - "4001:8080"
        volumes:
            - "/var/run/docker.sock:/var/run/docker.sock"
        deploy:
            placement:
                constraints: [node.role == manager]
